"""initial schema

Revision ID: 5b382a050396
Revises: 
Create Date: 2026-04-25 22:13:34.391362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b382a050396'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('ev_threshold', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('races', sa.Integer(), nullable=True),
    sa.Column('bet_races', sa.Integer(), nullable=True),
    sa.Column('invested', sa.Integer(), nullable=True),
    sa.Column('returned', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy', 'date_from', 'date_to', 'ev_threshold', 'model_version', name='uq_backtest_run_key')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_key', sa.String(length=8), nullable=False),
    sa.Column('held_on', sa.Date(), nullable=False),
    sa.Column('venue_code', sa.String(length=2), nullable=False),
    sa.Column('venue', sa.String(length=8), nullable=False),
    sa.Column('race_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('surface', sa.String(length=2), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=2), nullable=True),
    sa.Column('weather', sa.String(length=2), nullable=True),
    sa.Column('post_time', sa.String(length=5), nullable=True),
    sa.Column('head_count', sa.Integer(), nullable=True),
    sa.Column('pace_forecast', sa.String(length=1), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_key')
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index('ix_race_held_on', ['held_on'], unique=False)

    op.create_table('backtest_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('held_on', sa.Date(), nullable=False),
    sa.Column('bets', sa.Integer(), nullable=True),
    sa.Column('return_amount', sa.Integer(), nullable=True),
    sa.Column('hit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'race_id', name='uq_backtest_detail_run_race')
    )
    with op.batch_alter_table('backtest_detail', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_detail_run_held', ['run_id', 'held_on'], unique=False)

    op.create_table('backtest_sensitivity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ev_threshold', sa.Float(), nullable=False),
    sa.Column('bet_races', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'ev_threshold', name='uq_sensitivity_run_thr')
    )
    op.create_table('hjc_payout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id')
    )
    op.create_table('horse_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('horse_number', sa.Integer(), nullable=False),
    sa.Column('waku', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('jockey', sa.String(length=20), nullable=True),
    sa.Column('jockey_index', sa.Float(), nullable=True),
    sa.Column('weight_carried', sa.Float(), nullable=True),
    sa.Column('running_style', sa.Integer(), nullable=True),
    sa.Column('idm', sa.Float(), nullable=True),
    sa.Column('mid_position', sa.Integer(), nullable=True),
    sa.Column('late3f_position', sa.Integer(), nullable=True),
    sa.Column('goal_position', sa.Integer(), nullable=True),
    sa.Column('goal_io', sa.Integer(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('fukusho_odds', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('gate_miss_rate', sa.Float(), nullable=True),
    sa.Column('upset_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_number', name='uq_horse_entry_race_horse')
    )
    with op.batch_alter_table('horse_entry', schema=None) as batch_op:
        batch_op.create_index('ix_horse_entry_race', ['race_id'], unique=False)

    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horse_entry_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prob', sa.Float(), nullable=False),
    sa.Column('ev_tan', sa.Float(), nullable=True),
    sa.Column('ev_fuku', sa.Float(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_entry_id'], ['horse_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horse_entry_id', 'model_version', name='uq_prediction_horse_model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    with op.batch_alter_table('horse_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_horse_entry_race')

    op.drop_table('horse_entry')
    op.drop_table('hjc_payout')
    op.drop_table('backtest_sensitivity')
    with op.batch_alter_table('backtest_detail', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_detail_run_held')

    op.drop_table('backtest_detail')
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index('ix_race_held_on')

    op.drop_table('race')
    op.drop_table('backtest_run')
    # ### end Alembic commands ###
