"""add training_run

Revision ID: d332999781bf
Revises: 5b382a050396
Create Date: 2026-04-26 19:44:02.137935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd332999781bf'
down_revision: Union[str, Sequence[str], None] = '5b382a050396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('logloss', sa.Float(), nullable=True),
    sa.Column('auc', sa.Float(), nullable=True),
    sa.Column('brier', sa.Float(), nullable=True),
    sa.Column('hit_at_3', sa.Float(), nullable=True),
    sa.Column('train_time_seconds', sa.Integer(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('leaderboard_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    with op.batch_alter_table('training_run', schema=None) as batch_op:
        batch_op.create_index('ix_training_run_status', ['status'], unique=False)
        batch_op.create_index('ix_training_run_trained_at', ['trained_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_run', schema=None) as batch_op:
        batch_op.drop_index('ix_training_run_trained_at')
        batch_op.drop_index('ix_training_run_status')

    op.drop_table('training_run')
    # ### end Alembic commands ###
